<?php
	//应用挂载在后台的菜单，会写到权限表
	return [
		[
			'name'       => '博文管理' ,
			'module'     => 'blog' ,
			'controller' => 'Blogarticle' ,
			'action'     => 'none' ,
			'order'      => 190 ,
			'remark'     => '' ,
			'is_menu'    => 1 ,
			'son'        => [
				[
					'name'       => '添加博文' ,
					'module'     => 'blog' ,
					'controller' => 'Blogarticle' ,
					'action'     => 'add' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 0 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '设置字段' ,
					'module'     => 'blog' ,
					'controller' => 'Blogarticle' ,
					'action'     => 'setField' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 0 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '编辑博文' ,
					'module'     => 'blog' ,
					'controller' => 'Blogarticle' ,
					'action'     => 'edit' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 0 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '删除博文' ,
					'module'     => 'blog' ,
					'controller' => 'Blogarticle' ,
					'action'     => 'delete' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 0 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '博文列表' ,
					'module'     => 'blog' ,
					'controller' => 'Blogarticle' ,
					'action'     => 'dataList' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 1 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '预览文章' ,
					'module'     => 'blog' ,
					'controller' => 'Blogarticle' ,
					'action'     => 'preview' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 0 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '编辑博文' ,
					'module'     => 'blog' ,
					'controller' => 'Blogarticle' ,
					'action'     => 'editContent' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 0 ,
					'son'        => [] ,
				] ,
			] ,
		] ,
		[
			'name'       => '博客文章类型' ,
			'module'     => 'blog' ,
			'controller' => 'BlogType' ,
			'action'     => 'none' ,
			'order'      => 188 ,
			'remark'     => '' ,
			'is_menu'    => 0 ,
			'son'        => [
				[
					'name'       => '添加文章类型' ,
					'module'     => 'blog' ,
					'controller' => 'BlogType' ,
					'action'     => 'add' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 1 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '编辑文章类型' ,
					'module'     => 'blog' ,
					'controller' => 'BlogType' ,
					'action'     => 'edit' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 1 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '设置字段' ,
					'module'     => 'blog' ,
					'controller' => 'BlogType' ,
					'action'     => 'setField' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 1 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '删除文章类型' ,
					'module'     => 'blog' ,
					'controller' => 'BlogType' ,
					'action'     => 'delete' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 1 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '文章类型列表' ,
					'module'     => 'blog' ,
					'controller' => 'BlogType' ,
					'action'     => 'dataList' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 1 ,
					'son'        => [] ,
				] ,
			] ,
		] ,
		[
			'name'       => '博客标签' ,
			'module'     => 'blog' ,
			'controller' => 'BlogTag' ,
			'action'     => 'none' ,
			'order'      => 186 ,
			'remark'     => '' ,
			'is_menu'    => 0 ,
			'son'        => [
				[
					'name'       => '添加标签' ,
					'module'     => 'blog' ,
					'controller' => 'BlogTag' ,
					'action'     => 'add' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 1 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '删除标签' ,
					'module'     => 'blog' ,
					'controller' => 'BlogTag' ,
					'action'     => 'delete' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 1 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '编辑标签' ,
					'module'     => 'blog' ,
					'controller' => 'BlogTag' ,
					'action'     => 'edit' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 1 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '设置字段' ,
					'module'     => 'blog' ,
					'controller' => 'BlogTag' ,
					'action'     => 'setField' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 1 ,
					'son'        => [] ,
				] ,
				[
					'name'       => '标签列表' ,
					'module'     => 'blog' ,
					'controller' => 'BlogTag' ,
					'action'     => 'dataList' ,
					'order'      => 1 ,
					'remark'     => '' ,
					'is_menu'    => 1 ,
					'son'        => [] ,
				] ,
			] ,
		] ,
	];